In [10]:
from sklearn.datasets import load_iris
import numpy as np
from sklearn import tree

iris = load_iris()
test_idx = [0,50,100]

#training data
train_target = np.delete(iris.target,test_idx)
train_data = np.delete(iris.data,test_idx,axis=0)

#testing data
test_target = iris.target[test_idx]
test_data = iris.data[test_idx]

clf = tree.DecisionTreeClassifier()
clf.fit(train_data,train_target)
print(test_data,test_target)
print(clf.score(test_data,test_target))

[[5.1 3.5 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.3 3.3 6.  2.5]] [0 1 2]
1.0


In [7]:
prediction = clf.predict([[2,2.9,1,0.2]])
print(prediction)

[0]


In [4]:
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
from sklearn.model_selection import train_test_split
 
iris_dataset=load_iris()
 
X_train, X_test, y_train, y_test = train_test_split(iris_dataset["data"], iris_dataset["target"], random_state=0)
 
kn = KNeighborsClassifier(n_neighbors=2)
kn.fit(X_train, y_train)
 
x_new = np.array([[2, 2.9, 1, 0.2]])
prediction = kn.predict(x_new)
 
print("Predicted target value: {}\n".format(prediction))
print("Predicted feature name: {}\n".format(iris_dataset["target_names"][prediction]))
print("Test score: {:.2f}".format(kn.score(X_test, y_test)))


Predicted target value: [0]

Predicted feature name: ['setosa']

Test score: 0.97
