In [7]:
import cv2
img = cv2.imread("deku.png")
print(img)
img = cv2.resize(img,(480,480))
cv2.imshow("test",img)
cv2.waitKey(0)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


233

In [10]:
import numpy as np
import cv2
x = np.random.random((480,480,3))
cv2.imshow("Random",x)
cv2.waitKey(0)

233

In [12]:
import cv2
img = cv2.imread("book1.jpg")
img1 = cv2.imread("book1.jpg",0)
print(img.shape)
print(img1.shape)
img = cv2.resize(img,(480,480))
img1 = cv2.resize(img1,(480,480))
cv2.imshow("BGR",img)
cv2.imshow("GRAY",img1)
cv2.waitKey(0)

(1233, 1999, 3)
(1233, 1999)


233

In [14]:
# import the necessary packages
import numpy as np
import cv2

# load the image
image = cv2.imread("book8.jpg")
# define the list of boundaries
boundaries = [
	([17, 15, 100], [50, 56, 200]),
	([86, 31, 4], [220, 88, 50]),
	([25, 146, 190], [62, 174, 250]),
	([103, 86, 65], [145, 133, 128])
]
# loop over the boundaries
for (lower, upper) in boundaries:
    # create NumPy arrays from the boundaries
    lower = np.array(lower, dtype = "uint8")
    upper = np.array(upper, dtype = "uint8")

    # find the colors within the specified boundaries and apply
    # the mask
    mask = cv2.inRange(image, lower, upper)
    output = cv2.bitwise_and(image, image, mask = mask)
    image = cv2.resize(image,(480,480))
    output = cv2.resize(output,(480,480))
    cv2.imshow("images", np.hstack([image, output]))
    cv2.waitKey(0)